config/routes.rb
Rails.application.routes.draw do


  get 'admin/index'

  get 'admin/update'

  resources :apartments


  root 'apartments#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "admin" => "admin#index"
  put "admin/:id" => "admin#update"
  patch "admin/:id" => "admin#update"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.nil?
      # if no user logged in, use a dummy user, see later
      user ||= User.new
    end
    if user.has_role? :admin
      can :manage, :all
    else
      can [:read, :create], :all
      can :manage, Apartment, user_id: user.id
    end

  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  resourcify
end

app/models/apartment.rb
class Apartment < ApplicationRecord
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
validates_attachment :image, presence: true,
    content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] },
    size: { in: 0..10.megabytes }

  belongs_to :user, optional: true#add this line
  validates :user, presence: true # add this
  resourcify
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  after_create :assign_role

  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  has_many :apartments #add this line

  def assign_role
    add_role(:user)
  end


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]

      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize

  def index
    @users = User.all
  end

  def update
    user = User.find(params[:id])
    if user.has_role? :user
      user.remove_role(:user) # user only has one role
      user.add_role(:admin)
    else
      user.remove_role(:admin) # user only has one role
      user.add_role(:user)
    end
    redirect_to '/admin'
  end



  private

   def authorize
     if !current_user.has_role? :admin
       render plain:"No access for you!"
     end
   end
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :authenticate_user! #add this line
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource   # add this line
  # GET /apartments
  # GET /apartments.json
  def index

    if params[:search].nil? || params[:search].empty?
      @apartments = Apartment.all
    else
      @apartments = Apartment.basic_search(params[:search])
      render '/apartments/index.html'
    end
  end

  def search

  end
  # GET /apartments/1
  # GET /apartments/1.json
  def show

  end

  # GET /apartments/new
  def new
    @apartment = Apartment.new
    @user = current_user
  end

  # GET /apartments/1/edit
  def edit
    @user = current_user
  end

  # POST /apartments
  # POST /apartments.json
  def create
    @apartment = Apartment.new(apartment_params)
    @user = current_user
    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    @user = current_user
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to @apartment, notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    @apartment.destroy
    @user = current_user
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:street, :latitude, :longitude, :city, :zip, :state, :country, :name, :phone, :hours_contact, :image, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  respond_to :html, :json

  protect_from_forgery prepend: true
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to '/apartments/index'
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/admin/index.html.erb
<h1>Users</h1>
<table>
  <thead>
    <thead>
      <tr>
        <th>Email</th><th>Role</th>
      </tr>
    </thead>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.roles.last.name %></td>
      <td>
        <%= form_tag("/admin/" + user.id.to_s + "?role=admin", method: :PUT) do %>
          <input type="submit" value="Change Role"/>
        <% end %>
      </td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/update.html.erb
<h1>Admin#update</h1>
<p>Find me in app/views/admin/update.html.erb</p>

app/views/apartments/_form.html.erb
<%= form_with(model: apartment, local: true, html: { multipart: true }) do |form| %>
  <% if apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

      <ul>
      <% apartment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_area :street, id: :apartment_street %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, id: :apartment_latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, id: :apartment_longitude %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_area :city, id: :apartment_city %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.text_area :zip, id: :apartment_zip %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_area :state, id: :apartment_state %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_area :country, id: :apartment_country %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name, id: :apartment_name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_area :phone, id: :apartment_phone %>
  </div>

  <div class="field">
    <%= form.label :hours_contact %>
    <%= form.text_area :hours_contact, id: :apartment_hours_contact %>
  </div>

  <div class="field imageattach">
    <%= form.file_field :image, id: :attach %>
  </div>

  <input type="hidden" name="apartment[user_id]" id="user_id" value="<%=@user.id%>" >
  
  <div class="actions">
    <%= form.submit class: :buttontext %>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<h1>Edit Apartment</h1>
<div class="form">

<%= render 'form', apartment: @apartment %>

<%= link_to 'Show', @apartment %> |
<%= link_to 'Back', apartments_path %>

</div>

app/views/apartments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Apartments</h1>

<table>
  <thead>
    <tr>
      <th>Street</th>
      <th class="latitude">Latitude</th>
      <th>Longitude</th>
      <th>City</th>
      <th>Zip</th>
      <th class="state">State</th>
      <th>Country</th>
      <th>Name</th>
      <th>Phone</th>
      <th>Availability</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apartments.each do |apartment| %>
      <tr>
        <td><%= apartment.street %></td>
        <td class="latitude" id="latitude"><%= apartment.latitude %></td>
        <td id="longitude"><%= apartment.longitude %></td>
        <td><%= apartment.city %></td>
        <td><%= apartment.zip %></td>
        <td class="state"><%= apartment.state %></td>
        <td><%= apartment.country %></td>
        <td><%= apartment.name %></td>
        <td><%= apartment.phone %></td>
        <td><%= apartment.hours_contact %></td>
        <td><%= link_to 'Show', apartment %></td>
        <td><%= link_to 'Edit', edit_apartment_path(apartment) %></td>
        <td><%= link_to 'Destroy', apartment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="linksearch">

<%= link_to 'New Apartment', new_apartment_path %>
<br>
<br>

<form method="get" action="/apartments">
  <label for="search">Search apartments:</label>
  <input type="text" name="search" placeholder="Search By" >
  <input type="submit" value="Search">
</form>

</div>

<div id="map"></div>

app/views/apartments/new.html.erb
<h1>New Apartment</h1>
<div class="form">
  <%= render 'form', apartment: @apartment %>

  <%= link_to 'Back', apartments_path %>

</div>

app/views/apartments/show.html.erb
<div class="show">



<p id="notice"><%= notice %></p>

<p>
  <strong>Street:</strong>
  <%= @apartment.street %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @apartment.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @apartment.longitude %>
</p>

<p>
  <strong>City:</strong>
  <%= @apartment.city %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @apartment.zip %>
</p>

<p>
  <strong>State:</strong>
  <%= @apartment.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @apartment.country %>
</p>

<p>
  <strong>Name:</strong>
  <%= @apartment.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @apartment.phone %>
</p>

<p>
  <strong>Hours contact:</strong>
  <%= @apartment.hours_contact %>
</p>

<p>
  <%= link_to image_tag(@apartment.image.url(:large)), @apartment.image.url %>
</p>

<%= link_to 'Edit', edit_apartment_path(@apartment) %> |
<%= link_to 'Back', apartments_path %>
</div>

<style>
  /* Always set the map height explicitly to define the size of the div
   * element that contains the map. */
  #showmap {
    height: 50vh;
    width: 50vw;
  }
</style>

<input id="address" type="hidden" value="<%= @apartment.street %>,<%= @apartment.city %>,<%= @apartment.state %>,<%= @apartment.zip %>">

<div id="showmap"></div>

<script>
function initMap() {
  var map = new google.maps.Map(document.getElementById('showmap'), {
    zoom: 12,
    center: {lat: 32.70961, lng: -117.1579991}
  });

  var geocoder = new google.maps.Geocoder();
  // document.getElementById('submit').addEventListener('click',
  function geocodeme() {
    geocodeAddress(geocoder, map);
  };
  geocodeme()
}

function geocodeAddress(geocoder, resultsMap) {
  var address = document.getElementById('address').value;
  geocoder.geocode({'address': address}, function(results, status) {
    if (status === 'OK') {
      resultsMap.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
        map: resultsMap,
        position: results[0].geometry.location
      });
    } else {
      alert('Geocode was not successful for the following reason: ' + status);
    }
  });
}

</script>

<script async defer
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC9nhXMWs8RXF_OXTGrVAB7x-msZVhahGw&callback=initMap">
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apartmentapp</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <style>
    html, body {
      height: 100%;
      margin: 0;
      padding: 0;
    }


    </style>

  </head>

  <body>
    <ul class="hmenu">
  <%= render partial: 'devise/shared/menu' %>

  </ul>

    <%= yield %>


    <!-- <script src="script.js" defer></script> -->
  </body>
</html>

app/views/user/index.html.erb
<h1>Log In</h1>